Sprint 3
itim92/middle.messenger.praktikum.yandex pull request #3
Opened 2022-06-12 20:03 UTC by itim92

changelog:
- added my own jsx compiler
- refactoring all application to new templator (based on custom jsx compiler)
- added signin / signuo
- added ws support to messenger
- added some test cases

2022-06-13 05:42 UTC, agadoev requested changes
Привет)
Я ставил комментарии, на которые стоит обратить внимание и исправить. По большей части они на использование TypeScript и в целом стиля кода. Мне понравились твои тесты, и как ты реализовал шаблонизатор
Поправь то, что я заметил и двинемся дальше :)

2022-06-13 05:42 UTC, agadoev commented on package.json
> +    "mocha-jsdom": "^2.0.0",
Не стоит забывать про статичные версии зависимостей

2022-06-13 05:42 UTC, agadoev commented on packages/parcel-transformer-templator/index.js
> +    async transform({ asset, logger }) {
Я думаю неплохо было бы типизировать этот файл. При использовании может быть не совсем очевидно, что эта функция возвращает не asset, а [asset]

2022-06-13 05:42 UTC, agadoev commented on packages/templator-parser/src/code-generator/index.ts
> +    generateNodes(children: NodeType[]) {
К каждому методу стоит указать тип возвращаемого значения. Чем понятнее и очевиднее код - тем лучше

2022-06-13 05:42 UTC, agadoev commented on packages/templator-parser/src/code-generator/index.ts
> +            attributes: attributes ?? "null",
Есть ли возможность не использовать "null"? Если нет, то стоит хотя бы типизировать эту захардкоженную строку, например указать в сигнатуре метода createElement в аргументах так attributes: string | 'null', чтобы если другой программист случайно ошибется в слове null, typescript ему указал на ошибку

2022-06-13 05:42 UTC, agadoev commented on packages/templator-parser/src/tokenizer/index.ts
> +            let token: TokenType | undefined = undefined;
Можно не присваивать undefined, т.к. если явно не задать значение, то переменная по умолчанию будет undefined. Более красивым способом будет объявить тип как Nullable<TokenType>. 
type Nullable\<T> = T | null | undefined

2022-06-13 05:42 UTC, agadoev commented on src/components/Avatar/template.tpl
> +    const avatarUrl = src ? `https://ya-praktikum.tech/api/v2/resources${src}` : noAvatarImage;
Здесь логика того, какой будет ссылка на аватар. Нужно стараться не хранить логику в шаблонах вообще. Попробуй вынести это в компонент

2022-06-13 05:42 UTC, agadoev commented on src/components/Chat/index.ts
> +    get messageField() {
Здесь, как и в других методах этого класса, стоит учесть, что querySelector может вернуть null. Чтобы код был безопаснее и не "радовал" нас неожиданными null reference, стоит указать тип возращаемого значения из методов как HTMLElement | null. Или Nullable<HTMLElement>. И соответственно обработать случаи, когда querySelector возвращает null

2022-06-13 05:42 UTC, agadoev commented on src/components/Chat/template.tpl
> +    const currentChatUsersList = () => {
Стоит вынести эту логику в компонент Chat.ts, и передавать через props в шаблон
Проверь так же остальные шаблоны на то, чтобы там не было логики

2022-06-13 05:42 UTC, agadoev commented on src/components/ChatList/ChatListItem/template.tpl
> +    const itemClassName = "chat-item" + (isActive ? " active" : "");
Этот класс можно вынести и даже типизировать
type TItemClass = "active" | ""
Это нужно для того, чтобы если другой программист случайно допустит опечатку в названии класса, typescript ему указал на это. Без такой проверки в случае опечатки ошибку можно будет искать оочень долго)

2022-06-13 05:42 UTC, agadoev commented on src/components/ChatTrack/index.ts
> +// export type TrackType = {
Лучше убрать комментарии кода, потому что они загрязняют код. Хорошей практикой является держать код чистым, чтобы в нем не было ничего лишнего
Даже если этот код може в дальнейшнем понадобится, ты можешь записать его где-то в заметках, но оставлять закомментированный код не нужно

2022-06-13 05:42 UTC, agadoev commented on src/components/Form/fields/InputFile/template.tpl
> +        if (errorMessage) {
Почему не вернуть [<>...</>]?
Сейчас эта целочисленная константа может сбить с толку

2022-06-13 05:42 UTC, agadoev commented on src/components/Form/fields/InputText/index.ts
> +    //
Убрать закомментированный код

2022-06-13 05:42 UTC, agadoev commented on src/components/Form/fields/InputText/template.tpl
> +    const inputClassName = errorMessage ? " with-error" : "";
Вынести в компонент и типизировать

2022-06-13 05:42 UTC, agadoev commented on src/components/Form/template.tpl
> +        switch (element.type) {
Это тоже нужно вынести в компонент, т.к. сейчас эта функция не проверяется typescript'ом на соответствие типам

2022-06-13 05:42 UTC, agadoev commented on src/pages/Account/index.ts
> +            ["display_name", "oldPassword", "newPassword"].indexOf(name) !==
т.к. здесь простой массив строк, indexOf можно заменить на includes. Это повысит читаемость кода

2022-06-13 05:42 UTC, agadoev commented on src/pages/Account/index.ts
> +            case "first_name":
Использовать строковые константы нужно очень осторожно, потому что можно случайно допустить ошибку в слове, а заметить это бывает порой совсем непросто. Сейчас если изменить строку в case'ах, то typescript не подскажет нам, что мы можем допустить ошибку. Чтобы избежать этого, мы можем типизировать name не просто как string, а как множество конкретных строк "email" | "second_name" | "first_name" ... и тд. В таком случае если мы допустим опечатку, typescript нам сразу скажет об этом. Главное только не допустить опечаток при определении типа name)

2022-06-13 19:02 UTC, itim92 commented on package.json
> +    "mocha-jsdom": "^2.0.0",
Исправил

2022-06-13 19:02 UTC, itim92 commented on packages/parcel-transformer-templator/index.js
> +    async transform({ asset, logger }) {
Исправил

2022-06-13 19:02 UTC, itim92 commented on packages/templator-parser/src/code-generator/index.ts
> +    generateNodes(children: NodeType[]) {
Исправил

2022-06-13 19:02 UTC, itim92 commented on packages/templator-parser/src/code-generator/index.ts
> +            attributes: attributes ?? "null",
Исправил

2022-06-13 19:02 UTC, itim92 commented on packages/templator-parser/src/tokenizer/index.ts
> +            let token: TokenType | undefined = undefined;
Сделал Nullable

2022-06-13 19:02 UTC, itim92 commented on src/components/Form/fields/InputText/index.ts
> +    //
Убрал комменты

2022-06-13 19:03 UTC, itim92 commented on src/components/Form/fields/InputText/template.tpl
> +    const inputClassName = errorMessage ? " with-error" : "";
Исправил

2022-06-13 19:03 UTC, itim92 commented on src/pages/Account/index.ts
> +            ["display_name", "oldPassword", "newPassword"].indexOf(name) !==
Исправил

2022-06-13 19:03 UTC, itim92 commented on src/pages/Account/index.ts
> +            case "first_name":
Зарефакторил )

2022-06-13 20:32 UTC, itim92 commented on src/components/Chat/template.tpl
> +    const currentChatUsersList = () => {
currentChatUsers = currentChatUsers ?? []; - эту строчку вынес, а саму стрелочную функцию оставил, т.к. у меня в шаблонизаторе нет поддержки циклов (

2022-06-13 20:34 UTC, itim92 commented on src/components/Chat/index.ts
> +    get messageField() {
Исправил

2022-06-13 20:34 UTC, itim92 commented on src/components/Avatar/template.tpl
> +    const avatarUrl = src ? `https://ya-praktikum.tech/api/v2/resources${src}` : noAvatarImage;
Исправил

2022-06-13 20:37 UTC, itim92 commented on src/components/ChatList/ChatListItem/template.tpl
> +    const itemClassName = "chat-item" + (isActive ? " active" : "");
Исправил

2022-06-13 20:37 UTC, itim92 commented on src/components/Form/fields/InputFile/template.tpl
> +        if (errorMessage) {
исправил

2022-06-13 20:38 UTC, itim92 commented on src/components/ChatTrack/index.ts
> +// export type TrackType = {
исправил

2022-06-14 20:44 UTC, agadoev approved these changes
Привет)
Супер, спасибо за работу, я ее принимаю. Удачи в четвертом спринте)

2022-06-15 06:32 UTC, itimka-alars commented
> Привет) Супер, спасибо за работу, я ее принимаю. Удачи в четвертом спринте)

Спасибо тебе :)

2022-06-26 12:31 UTC, merged